version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - brainbot_network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - brainbot_network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3001:3000'
    env_file:
      - .env
    networks:
      - brainbot_network

networks:
  brainbot_network:
    driver: bridge

volumes:
  redis_data: